server:
  port: 8768

spring:
  application:
    name: service-zuul


  http:
    encoding:
      charset: utf-8
      enabled: true

  output:
    ansi:
      enabled: always

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: gree
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: user-feign
    api-b:
      path: /menu/**
      serviceId: menu-feign
    api-c:
      path: /material/**
      serviceId: material-feign
  #zuul默认会丢弃原来的session并且生成新的session，所以有次配置
  sensitive-headers: "*"
#  retryable: false
#
#  add-proxy-headers: true
#  ignored-services: "*"



security:
  oauth2:
    client:
      access-token-uri: http://localhost:8769/auth/oauth/token
      user-authorization-uri: http://localhost:8769/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:8769/member
      prefer-token-info: false

logging:
  level:
    com.gree:
      debug
