server:
  port: 8769

spring:
  application:
    name: gree-auth

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: gree
      profile: dev

yhm:
  oauth2:
    token:
      store:
        type: authJwt

encrypt:
  key-store:
    location: classpath:greeerp.jks
    secret: gree!23
    password: gree!23
    alias: greeerp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
