spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  banner:
    charset: UTF-8

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: WWJ19950811
    lettuce:
      pool:
        max-active: 32
        max-wait: 3004
        max-idle: 16
        min-idle: 8

    timeout: 10ms

  local-redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: WWJ19950811
    lettuce:
      pool:
        max-active: 16
        max-wait: 100
        max-idle: 8
        min-idle: 4

    timeout: 10ms



feign:
  hystrix:
    enabled: false

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8769/oauth/token
      user-authorization-uri: http://localhost:8769/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:8769/api/member
      prefer-token-info: false

