spring:
  application:
    #服务与服务之间相互调用一般都是根据这个name
    name: client-say-hi

  output:
    ansi:
      enabled: always

  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    service:
      name: client-say-mouzi
  sleuth:
    sampler:
      probability: 1.0


  #消息队列
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: jinyu
    password: 123456

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: gree
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

security:
  oauth2:
    resource:
      id: gree-member
      user-info-uri: http://localhost:8769/api/member
      prefer-token-info: false



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.gree.dao:
      debug
    com.gree.aspect:
      debug

